/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as QuickstartsRouteImport } from './routes/quickstarts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TutorialsRouteImport } from './routes/tutorials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickstartsRoute = QuickstartsRouteImport.update({
  id: '/quickstarts',
  path: '/quickstarts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/playground': typeof PlaygroundRoute
  '/quickstarts': typeof QuickstartsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/tutorials': typeof TutorialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/playground': typeof PlaygroundRoute
  '/quickstarts': typeof QuickstartsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/tutorials': typeof TutorialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/playground': typeof PlaygroundRoute
  '/quickstarts': typeof QuickstartsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/tutorials': typeof TutorialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concepts'
    | '/playground'
    | '/quickstarts'
    | '/settings'
    | '/templates'
    | '/tutorials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concepts'
    | '/playground'
    | '/quickstarts'
    | '/settings'
    | '/templates'
    | '/tutorials'
  id:
    | '__root__'
    | '/'
    | '/concepts'
    | '/playground'
    | '/quickstarts'
    | '/settings'
    | '/templates'
    | '/tutorials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptsRoute: typeof ConceptsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  QuickstartsRoute: typeof QuickstartsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  TutorialsRoute: typeof TutorialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quickstarts': {
      id: '/quickstarts'
      path: '/quickstarts'
      fullPath: '/quickstarts'
      preLoaderRoute: typeof QuickstartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptsRoute: ConceptsRoute,
  PlaygroundRoute: PlaygroundRoute,
  QuickstartsRoute: QuickstartsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  TutorialsRoute: TutorialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
